package com.rain.govminutes.audio;

import java.io.File;
import java.io.IOException;
import java.util.*;

public final class Diarizer {
    public static final class Segment { public long startMs, endMs; public int speaker; public double confidence; public Segment(long s,long e,int sp,double c){startMs=s;endMs=e;speaker=sp;confidence=c;} }
    private static final int SR=16000; private static final int MAX_SPEAKERS=8;
    public static List<Segment> diarize(File wav,int inputSampleRate)throws IOException{
        short[] raw=WavIO.readPcm16(wav); float[] x=downsample(raw,inputSampleRate,SR); List<Turn> turns=findSpeechTurns(x); if(turns.isEmpty())return Collections.emptyList();
        for(Turn t:turns)t.feature=turnFeature(x,t.s,t.e); normalize(turns); List<Cluster> clusters=new ArrayList<>();
        for(Turn t:turns){ int best=-1; double bd=Double.MAX_VALUE; for(int i=0;i<clusters.size();i++){double d=dist(t.feature,clusters.get(i).centroid);if(d<bd){bd=d;best=i;}} double dur=(t.e-t.s)/(double)SR; boolean strongNewEvidence=dur>=3.0 && t.meanRms>t.speechThreshold*1.15; double newThreshold=0.52; if(best<0){clusters.add(new Cluster(t.feature,t.e));t.cluster=0;t.distance=0;} else if(bd>newThreshold && strongNewEvidence && clusters.size()<MAX_SPEAKERS){clusters.add(new Cluster(t.feature,t.e));t.cluster=clusters.size()-1;t.distance=0;} else {clusters.get(best).add(t.feature,t.e);t.cluster=best;t.distance=bd;} }
        boolean changed=true; while(changed){changed=false;outer:for(int i=0;i<clusters.size();i++)for(int j=i+1;j<clusters.size();j++){ if(dist(clusters.get(i).centroid,clusters.get(j).centroid)<0.34){ clusters.get(i).merge(clusters.get(j)); for(Turn t:turns){if(t.cluster==j)t.cluster=i;else if(t.cluster>j)t.cluster--;} clusters.remove(j);changed=true;break outer; } }}
        for(int i=1;i+1<turns.size();i++){ Turn t=turns.get(i);double dur=(t.e-t.s)/(double)SR; if(dur<3.0 && turns.get(i-1).cluster==turns.get(i+1).cluster)t.cluster=turns.get(i-1).cluster; }
        Map<Integer,Integer> map=new LinkedHashMap<>();int next=1;List<Segment> out=new ArrayList<>(); for(Turn t:turns){if(!map.containsKey(t.cluster))map.put(t.cluster,next++);int sp=map.get(t.cluster);double conf=Math.max(.35,Math.min(.95,1.0-t.distance));out.add(new Segment(t.s*1000L/SR,t.e*1000L/SR,sp,conf));} return mergeAdjacent(out);
    }
    private static List<Turn> findSpeechTurns(float[]x){ int frame=SR/10;int n=(x.length+frame-1)/frame;double[]r=new double[n];for(int f=0;f<n;f++)r[f]=rms(x,f*frame,Math.min(x.length,(f+1)*frame)); double[]ss=r.clone();Arrays.sort(ss);double noise=ss[Math.min(ss.length-1,Math.max(0,ss.length/5))];double th=Math.max(.0075,noise*1.75); boolean[]speech=new boolean[n];for(int i=0;i<n;i++)speech[i]=r[i]>th; for(int i=1;i<n-1;i++)if(!speech[i]&&speech[i-1]&&speech[i+1])speech[i]=true; for(int gap=0;gap<5;gap++)for(int i=1;i<n-1;i++)if(!speech[i]&&speech[i-1]){int j=i;while(j<n&&!speech[j]&&j-i<5)j++;if(j<n&&speech[j])for(int k=i;k<j;k++)speech[k]=true;} List<Turn>out=new ArrayList<>();int i=0;while(i<n){while(i<n&&!speech[i])i++;if(i>=n)break;int s=i;while(i<n&&speech[i])i++;int e=i;long ms=(e-s)*100L;if(ms>=900){int ssamp=s*frame,esamp=Math.min(x.length,e*frame);Turn t=new Turn(ssamp,esamp);t.meanRms=rms(x,ssamp,esamp);t.speechThreshold=th;out.add(t);}} return out; }
    private static double[] turnFeature(float[]x,int s,int e){ int win=SR;int hop=SR/2;List<double[]>v=new ArrayList<>(); if(e-s<win)v.add(localFeature(x,s,e)); else for(int p=s;p+win<=e;p+=hop)v.add(localFeature(x,p,p+win)); int d=v.get(0).length;double[]o=new double[d]; for(int j=0;j<d;j++){double[]a=new double[v.size()];for(int i=0;i<a.length;i++)a[i]=v.get(i)[j];Arrays.sort(a);o[j]=a[a.length/2];} return o; }
    private static double[] localFeature(float[]x,int s,int e){ double[]freq={140,220,340,520,780,1150,1650,2300,3200,4300,5600,7000};double[]bands=new double[freq.length];double sum=1e-12; for(int k=0;k<freq.length;k++){bands[k]=goertzel(x,s,e,SR,freq[k]);sum+=bands[k];} double[]f=new double[17];double meanLog=0;for(int k=0;k<bands.length;k++){f[k]=Math.log((bands[k]+1e-12)/sum);meanLog+=f[k];}meanLog/=bands.length;for(int k=0;k<bands.length;k++)f[k]-=meanLog; int z=0;for(int i=s+1;i<e;i++)if((x[i]>=0)!=(x[i-1]>=0))z++;f[12]=(double)z/Math.max(1,e-s); Pitch p=pitch(x,s,e);f[13]=p.hz/300.0;f[14]=p.strength; double low=0,high=0;for(int k=0;k<6;k++)low+=Math.exp(f[k]);for(int k=6;k<12;k++)high+=Math.exp(f[k]);f[15]=Math.log((low+1e-9)/(high+1e-9)); f[16]=Math.log(rms(x,s,e)+1e-8)*0.08; return f; }
    private static Pitch pitch(float[]x,int s,int e){int min=SR/320,max=SR/75;double best=0;int bestLag=0;for(int lag=min;lag<=max;lag+=2){double ab=0,aa=0,bb=0;for(int i=s;i+lag<e;i+=4){double a=x[i],b=x[i+lag];ab+=a*b;aa+=a*a;bb+=b*b;}double q=ab/Math.sqrt(aa*bb+1e-12);if(q>best){best=q;bestLag=lag;}}double hz=bestLag>0?SR/(double)bestLag:0;return new Pitch(hz,best);}
    private static double goertzel(float[]x,int s,int e,int sr,double fr){double w=2*Math.PI*fr/sr,c=2*Math.cos(w),q0=0,q1=0,q2=0;for(int i=s;i<e;i+=3){q0=c*q1-q2+x[i];q2=q1;q1=q0;}return Math.max(0,q1*q1+q2*q2-c*q1*q2)/Math.max(1,(e-s)/3);}
    private static void normalize(List<Turn>t){int d=t.get(0).feature.length;double[]m=new double[d],sd=new double[d];for(Turn a:t)for(int j=0;j<d;j++)m[j]+=a.feature[j];for(int j=0;j<d;j++)m[j]/=t.size();for(Turn a:t)for(int j=0;j<d;j++){double q=a.feature[j]-m[j];sd[j]+=q*q;}for(int j=0;j<d;j++)sd[j]=Math.sqrt(sd[j]/t.size()+1e-5);for(Turn a:t)for(int j=0;j<d;j++)a.feature[j]=(a.feature[j]-m[j])/sd[j];}
    private static double dist(double[]a,double[]b){double dot=0,aa=0,bb=0;for(int i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return 1-dot/Math.sqrt(aa*bb+1e-12);}
    private static double rms(float[]x,int s,int e){double q=0;for(int i=s;i<e;i++)q+=x[i]*x[i];return Math.sqrt(q/Math.max(1,e-s)+1e-12);}
    private static float[]downsample(short[]in,int sr,int target){if(sr==target){float[]o=new float[in.length];for(int i=0;i<in.length;i++)o[i]=in[i]/32768f;return o;}int n=(int)((long)in.length*target/sr);float[]o=new float[n];for(int i=0;i<n;i++){double p=(double)i*sr/target;int a=(int)p,b=Math.min(in.length-1,a+1);double u=p-a;o[i]=(float)(((1-u)*in[a]+u*in[b])/32768.0);}return o;}
    private static List<Segment>mergeAdjacent(List<Segment>x){List<Segment>r=new ArrayList<>();for(Segment s:x){if(!r.isEmpty()){Segment p=r.get(r.size()-1);if(p.speaker==s.speaker&&s.startMs<=p.endMs+700){p.endMs=s.endMs;p.confidence=(p.confidence+s.confidence)/2;continue;}}r.add(s);}return r;}
    private static final class Turn{int s,e,cluster;double meanRms,speechThreshold,distance;double[]feature;Turn(int s,int e){this.s=s;this.e=e;}}
    private static final class Cluster{double[]centroid;int n=1,last;Cluster(double[]f,int e){centroid=f.clone();last=e;}void add(double[]f,int e){for(int i=0;i<f.length;i++)centroid[i]=(centroid[i]*n+f[i])/(n+1);n++;last=e;}void merge(Cluster o){for(int i=0;i<centroid.length;i++)centroid[i]=(centroid[i]*n+o.centroid[i]*o.n)/(n+o.n);n+=o.n;last=Math.max(last,o.last);}}
    private static final class Pitch{double hz,strength;Pitch(double h,double s){hz=h;strength=s;}}
}
